#!/bin/sh

_copyright(){ echo "
  ozh lightweight shell extensions
  2008-2014 - anx @ ulzq de (Sebastian Glaser)
  Licensed under GNU GPL v3"; }
_license(){ echo "
  ozh is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2, or (at your option)
  any later version.

  ozh is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this software; see the file COPYING.  If not, write to
  the Free Software Foundation, Inc., 59 Temple Place, Suite 330,
  Boston, MA 02111-1307 USA

  http://www.gnu.org/licenses/gpl.html"; }
[ -f "$OZH/motd" ] && . "$OZH/motd" || {
  printf "\n$bblue code.ulzq.de/ozh $byellow                $R                  ${byellow} $R   ${byellow}   $R  ${byellow}   $RN"
  printf "$byellow                                  $R   ${byellow}   $R   ${byellow}    $R   ${byellow}   $R   ${byellow}   $R  ${byellow}   $RN"
  printf "$byellow                                  $R    ${byellow}  $R   ${byellow}   $R   ${byellow}    $R        ${byellow}   $RN"
  printf "$byellow                                   $R      ${byellow}   $R            ${byellow}   $R  ${byellow}   $RN"
  printf "$bblack$white ozh - one zhell to rule them all and in the darkness bind them $RN"
  # too slow
  # is_set cpu && printf "$bblack$white CPU $R \x1b[10G $(cpubar)\n"
  # is_set ctop && printf "$bblack$white TOP $R \x1b[10G $bblue ";ctop | tr '\n' ' '; printf " $RN"
  # printf "$bblack$white MEM $R \x1b[14G $bblue $(mtop | tr '\n' ' ') $RN"
  printf "$(oz printenv)\n"; }