#!/bin/sh

_copyright(){ echo "
  ozh lightweight shell extensions
  2008-2016 - anx @ ulzq de (Sebastian Glaser)
  Licensed under GNU GPL v3"; }
_license(){ echo "
  ozh is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2, or (at your option)
  any later version.

  ozh is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this software; see the file COPYING.  If not, write to
  the Free Software Foundation, Inc., 59 Temple Place, Suite 330,
  Boston, MA 02111-1307 USA

  http://www.gnu.org/licenses/gpl.html"; }

[ -n "$OZH_INSTALL" ] && _install_shell(){
  busybox grep -q "^shell/shell\$" "$OZH/libs" 2>/dev/null || echo "shell/shell" >> "$OZH/libs"
  oz install +only +prefix shell zsh bash ash scm +lib abstracts aliases apt util -only motd
  oz hook set precmd zzprompt 'PS1=$(_prompt_ozh|_prompt_escape)'
  _setup; }

_ps_linux(){ cat "/proc/$$/cmdline" | tr "\00" ' ' | busybox awk '{gsub(/^-/,"",$0);print $1;exit}'; }
_ps_minop(){ ps -o pid,comm -p $$ | busybox awk 'BEGIN{getline;getline;print $1}'; }
_ps_me(){ ps -o pid,comm | busybox awk '{if($1==1336){$1="";gsub(/^ /,"",$0);print $0}}'; }

_setup(){
  export OZ_SHELL=$(basename "$(_ps_linux)")
  [ "$OZ_SHELL" = "busybox" ] && OZ_SHELL=ash
  [ -f "$OZH/shell/$OZ_SHELL" ] && . "$OZH/shell/$OZ_SHELL"
  [ -n "$OZ_LIB" ] && OZ_SHELL_COLOR=false;
  return 0; }

title(){
  if echo "$TERM" | busybox grep -q "screen";then
      echo -ne $'\033k'$1$'\033\\'
      echo -ne $'\033]0;'$2$'\a'
  elif os_tinycore;then echo -n''
  elif echo "$TERM" | busybox grep -q "xterm";then echo -ne "\033]0;$@\007";
  else print -Pn "\e]2;$a $1 $2\a";fi; }

export OZ_SHELL='c'
export OZ_SHELL_COLOR=false
export OZ_SHELL_GLOBAL_ALIASES=false
export OZ_SHELL_SUFFIX_ALIASES=false
export OZ_PROMPT_USER_COLOR="${green}"

[ "$USER" = "root" ] && OZ_PROMPT_USER_COLOR="${red}"

oz default BROWER w3m
oz default LS_COLORS
oz default EDITOR vim
oz default TERMINAL xterm
oz default PAGER less

_prompt_ozh(){ local pwd=$(pwd); printf "\
$bblack$white$bold$(date +%H%M)\
$OZ_PROMPT_USER_COLOR$USER$blue@$(printf "$HOST"|head -c3)\
$bblack$yellow$(dirname "$pwd"|tr \/ '\n'|cut -b 1|tr -d '\n')\
$white$bgreen$(basename "$pwd"|tail -c8)$R "; }
_prompt_ozh_small(){ printf "$bblack$black$bold$(date +%H%M): $R "; }

_prompt(){ oz hook run prompt; }
_uprompt(){ oz hook run uprompt; }
_prompt_escape(){ busybox awk '
  BEGIN{RS="\x1b"}{for(i=0;i<length($0)+1;i++){b=substr($0,0,i);e=substr($0,i+1);if(match(substr(b,i,1),/[a-zA-Z]/))break};printf "%s%s%s%s",s,b,q,e;s="\\[\x1b";q="\\]"}'; }

_setup

preexec(){ oz hook run preexec; }
precmd(){  oz hook run precmd; }
